import type { Language } from "@/lib/i18n";

export type ScoutPageKey =
  | "home"
  | "howItWorks"
  | "companies"
  | "agencies"
  | "about"
  | "demo";

export const scoutPaths: Record<ScoutPageKey, Record<Language, string>> = {
  home: { nl: "/", en: "/en" },
  howItWorks: { nl: "/hoe-het-werkt", en: "/en/how-it-works" },
  companies: { nl: "/voor-bedrijven", en: "/en/for-companies" },
  agencies: { nl: "/voor-recruitmentbureaus", en: "/en/for-recruitment-agencies" },
  about: { nl: "/over", en: "/en/about" },
  demo: { nl: "/demo", en: "/en/demo" },
};

export const scoutUi = {
  nl: {
    product: "Scout",
    howItWorks: "Hoe het werkt",
    audience: "Voor wie",
    companies: "Bedrijven",
    agencies: "Recruitmentbureaus",
    about: "Over Philoo",
    contact: "Contact",
    demo: "Plan een demo",
    menu: "Menu openen",
    close: "Menu sluiten",
    language: "Taal kiezen",
    primaryNavigation: "Hoofdnavigatie",
    mobileNavigation: "Mobiele navigatie",
    footerNavigation: "Voettekstnavigatie",
    privacy: "Privacybeleid",
    terms: "Algemene voorwaarden",
    copyright: "© 2026 Philoo. Alle rechten voorbehouden.",
  },
  en: {
    product: "Scout",
    howItWorks: "How it works",
    audience: "Who it’s for",
    companies: "Hiring teams",
    agencies: "Recruitment agencies",
    about: "About",
    contact: "Contact",
    demo: "Book a demo",
    menu: "Open menu",
    close: "Close menu",
    language: "Choose language",
    primaryNavigation: "Primary navigation",
    mobileNavigation: "Mobile navigation",
    footerNavigation: "Footer navigation",
    privacy: "Privacy",
    terms: "Terms",
    copyright: "© 2026 Philoo. All rights reserved.",
  },
} satisfies Record<Language, Record<string, string>>;

export const scoutHomeCopy = {
  nl: {
    eyebrow: "Software om kandidaten te vinden",
    headline: "Vul je vacatures sneller in.",
    lead: "Vertel wie je zoekt. Scout vindt passende kandidaten.",
    primaryCta: "Plan een demo",
    secondaryCta: "Bekijk hoe het werkt",
    note: "Je hebt geen vacaturetekst nodig om te beginnen.",
    visualPrompt: "We zoeken iemand die zelf nieuwe klanten binnenhaalt.",
    visualFeedback: "Meer ervaring met zelf verkopen.",
    visualLabel: "Illustratie",
    stepsTitle: "Zo werkt Scout",
    steps: [
      ["Vertel wie je zoekt", "Beschrijf het werk, het team en welke ervaring belangrijk is."],
      ["Bekijk kandidaten", "Bekijk relevante profielinformatie en geef aan wat wel en niet past."],
      ["Kies wie je benadert", "Scout gebruikt je feedback bij het verdere zoeken. Jij bepaalt wie je benadert."],
    ],
    candidateTitle: "Zie welke ervaring bij je vraag aansluit.",
    candidateIntro: "Bekijk relevante ervaring uit het profiel en zie welke vragen nog openstaan.",
    candidateLabel: "Kandidaatprofiel",
    candidateDisclosure: "Zo toont Scout een profiel",
    candidateName: "Alex Morgan",
    candidateRole: "Business Development Manager",
    candidateLocation: "Rotterdam",
    whyLabel: "Relevante ervaring",
    why: "Vond en benaderde in recente functies zelf nieuwe zakelijke klanten.",
    checkLabel: "Nog te bespreken",
    check: "Interesse in deze vacature, salarisverwachting en beschikbaarheid.",
    evidenceToggle: "Bekijk de profielinformatie",
    evidence: [
      "Vond en benaderde zelf mogelijke zakelijke klanten.",
      "Voerde de eerste commerciële gesprekken.",
    ],
    audienceTitle: "Bekijk wat Scout voor je team of bureau doet.",
    audienceIntro: "Lees hoe Scout werkt voor een intern recruitmentteam of een recruitmentbureau.",
    audiences: [
      ["Bedrijven", "Combineer de kennis van de leidinggevende met de aanpak van de recruiter.", "Bekijk Scout voor bedrijven"],
      ["Recruitmentbureaus", "Gebruik de feedback van je klant bij het verdere zoeken.", "Bekijk Scout voor recruitmentbureaus"],
    ],
    finalTitle: "Bekijk wat Scout voor je vacature kan doen.",
    finalBody: "Neem een vacature mee naar de demo.",
    finalNote: "We bekijken samen hoe Scout zoekt en selecteert.",
  },
  en: {
    eyebrow: "Candidate sourcing software",
    headline: "Fill your vacancies faster.",
    lead: "Tell Philoo who you need. Scout finds relevant candidates.",
    primaryCta: "Book a demo",
    secondaryCta: "See how it works",
    note: "No job description needed to start.",
    visualPrompt: "We need someone who wins new clients.",
    visualFeedback: "More experience selling directly.",
    visualLabel: "Illustration",
    stepsTitle: "How Scout works",
    steps: [
      ["Explain who you need", "Describe what matters for the role and team in your own words."],
      ["Review candidates", "Your response to profiles helps Scout refine the search direction."],
      ["Choose who to contact", "Review the shortlist and decide who you want to approach."],
    ],
    candidateTitle: "Know why someone is worth a conversation.",
    candidateIntro: "Scout separates relevant experience from questions that still need an answer.",
    candidateLabel: "Candidate profile",
    candidateDisclosure: "Fictional profile",
    candidateName: "Alex Morgan",
    candidateRole: "Business Development Manager",
    candidateLocation: "Rotterdam",
    whyLabel: "Why review",
    why: "Documented experience in direct client acquisition and selling directly.",
    checkLabel: "Still to check",
    check: "Interest in the role, salary expectations and availability.",
    evidenceToggle: "Why this candidate may fit",
    evidence: [
      "Personally opened new B2B accounts in recent roles.",
      "Personally found potential clients and led the first commercial conversations.",
    ],
    audienceTitle: "See Scout for the way you recruit.",
    audienceIntro: "The same focused search approach, shaped for your team or agency.",
    audiences: [
      ["Hiring teams", "Bring hiring-manager context and recruiter input together.", "Explore Scout for hiring teams"],
      ["Recruitment agencies", "Turn client feedback into a more focused search direction.", "Explore Scout for agencies"],
    ],
    finalTitle: "Find your next candidate.",
    finalBody: "For hiring managers, recruiters and recruitment agencies.",
    finalNote: "In the demo, we will review a search brief and shortlist together.",
  },
} as const;

export const scoutPageCopy = {
  howItWorks: {
    nl: {
      eyebrow: "Hoe het werkt",
      title: "Zo vindt Scout passende kandidaten.",
      intro: "Vertel wie je zoekt en bekijk de eerste kandidaten. Geef aan wat wel en niet past. Scout gebruikt je feedback om verder te zoeken. Jij kiest wie je benadert.",
      heroUser: "We zoeken iemand die zelf nieuwe klanten opbouwt.",
      heroScout: "Welke ervaring was bij eerdere kandidaten nog te licht?",
      sectionTitle: "Van zoekvraag naar een nieuwe selectie.",
      demoTitle: "Zie hoe Scout je feedback gebruikt.",
      demoIntro: "Doorloop de vier stappen of speel de uitleg af. Je kunt op elk moment naar een andere stap gaan.",
      deliverableLabel: "Wat je ziet",
      deliverableTitle: "Relevante profielinformatie en open vragen.",
      deliverableIntro: "Scout laat zien welke ervaring in het profiel staat en welke belangrijke vragen je nog moet bespreken.",
      deliverableItems: [
        ["Ervaring uit het profiel", "Bekijk werkzaamheden en ervaring die bij je vraag aansluiten."],
        ["Vragen die openstaan", "Interesse, salarisverwachting en beschikbaarheid bespreek je met de kandidaat."],
        ["Jouw keuze", "Je beoordeelt de kandidaten en bepaalt wie je benadert."],
      ],
      steps: [
        {
          number: "01",
          title: "Leg uit wat de functie vraagt.",
          body: "Beschrijf het werk in gewone taal. Heb je al een vacaturetekst, dan kun je die ook gebruiken.",
          prompt: "Zelf potentiële klanten vinden, eerste gesprekken voeren en deals overdragen.",
        },
        {
          number: "02",
          title: "Bekijk de eerste kandidaten.",
          body: "Geef aan wat wel en niet past en welke ervaring je belangrijker vindt.",
          prompt: "Zelf nieuwe klanten binnenhalen; een team aansturen is minder belangrijk.",
        },
        {
          number: "03",
          title: "Bekijk de selectie na je feedback.",
          body: "Scout zoekt verder met je feedback. Jij bekijkt de kandidaten en kiest wie je benadert.",
          prompt: "Nieuwe kandidaten om te beoordelen.",
        },
      ],
      finalTitle: "Wil je zien hoe Scout werkt voor je vacature?",
      finalBody: "Neem een lastige vacature mee naar de demo.",
      finalNote: "We laten zien welke informatie je geeft, wat Scout daarmee doet en welke keuze bij jou blijft.",
    },
    en: {
      eyebrow: "How it works",
      title: "How Scout finds relevant candidates.",
      intro: "Explain who you need. Review the first candidates and say what fits and what does not. Scout uses your feedback to continue the search.",
      heroUser: "We need someone who can build new client relationships.",
      heroScout: "Which experience was too light in earlier candidates?",
      sectionTitle: "One search, with more direction at every step.",
      demoTitle: "See how feedback changes the search direction.",
      demoIntro: "Move through the demo one stage at a time or play the short walkthrough. You can jump to any stage whenever you like.",
      deliverableLabel: "What you receive",
      deliverableTitle: "A shortlist with reasons, evidence and open questions.",
      deliverableIntro: "Scout shows why a profile may be relevant without presenting unknown information as fact.",
      deliverableItems: [
        ["Known information", "Relevant experience and supporting profile information."],
        ["Open questions", "Interest, salary expectations and availability still need a conversation."],
        ["Your decision", "You assess the profile and decide who to contact."],
      ],
      steps: [
        {
          number: "01",
          title: "Start with the work, not just the title.",
          body: "Describe the role in plain language, or use a job description if you already have one.",
          prompt: "Find potential clients, lead first conversations and hand over signed deals.",
        },
        {
          number: "02",
          title: "A few profiles make the direction clearer.",
          body: "Explain what fits, what does not and which experience matters more.",
          prompt: "More direct selling, less team management.",
        },
        {
          number: "03",
          title: "Get a shortlist you can act on.",
          body: "See relevant experience, points to consider and open questions. You choose who to contact.",
          prompt: "Focused shortlist ready to review.",
        },
      ],
      finalTitle: "Ready to explore your next search?",
      finalBody: "Bring a difficult vacancy to the demo.",
      finalNote: "We will show how context, feedback and candidate evidence work together.",
    },
  },
  companies: {
    nl: {
      eyebrow: "Voor bedrijven",
      title: "Vind de mensen die je team nodig heeft.",
      intro: "De leidinggevende weet wat het werk vraagt. De recruiter weet hoe de zoektocht verloopt. Scout helpt je beide perspectieven te gebruiken bij het zoeken en selecteren.",
      sectionTitle: "Maak samen duidelijk wat echt telt.",
      points: [
        ["Leg uit wat de functie vraagt", "Beschrijf wat iemand moet bereiken en welke ervaring belangrijk is."],
        ["Bekijk de eerste kandidaten", "Bespreek wat wel en niet past en geef die feedback aan Scout."],
        ["Kies wie je benadert", "Scout zoekt verder met je feedback. Je team bepaalt wie contact opneemt."],
      ],
      focusTitle: "Maak de zoekvraag concreet.",
      needLabel: "Wat de functie vraagt",
      need: "Zelf nieuwe zakelijke klanten vinden in een groeiende organisatie.",
      checkLabel: "Wat nog te bespreken is",
      check: "Interesse in de vacature, salarisverwachting en beschikbaarheid.",
      finalTitle: "Bekijk hoe Scout werkt voor je team.",
      finalBody: "Neem een vacature mee en zie hoe Scout jullie input gebruikt bij het zoeken en selecteren.",
    },
    en: {
      eyebrow: "For hiring teams",
      title: "Find the people your team actually needs.",
      intro: "The hiring manager knows the work. The recruiter knows the search. Scout helps turn their input into a focused shortlist.",
      sectionTitle: "Get aligned on what really matters.",
      points: [
        ["Explain the work", "Share what someone needs to achieve and which experience will help."],
        ["Review the direction", "Discuss a few profiles and make preferences concrete."],
        ["Choose who to contact", "Review relevant candidates and keep the decision with your team."],
      ],
      focusTitle: "Keep the search focused.",
      needLabel: "What the team needs",
      need: "Personally winning clients in a growing B2B environment.",
      checkLabel: "What still needs a conversation",
      check: "Interest, salary expectations and availability.",
      finalTitle: "Move your next search forward.",
      finalBody: "See how Scout turns your team’s input into a focused shortlist.",
    },
  },
  agencies: {
    nl: {
      eyebrow: "Voor recruitmentbureaus",
      title: "Zoek kandidaten op basis van wat je klant nodig heeft.",
      intro: "Leg vast wat je klant zoekt. Bekijk kandidaten, geef feedback en kies wie je benadert.",
      sectionTitle: "Van intake naar kandidaten die je kunt beoordelen.",
      points: [
        ["Leg vast wie je klant zoekt", "Beschrijf het werk, het team en welke ervaring belangrijk is."],
        ["Bekijk de eerste kandidaten", "Geef aan wat wel en niet past en wat Scout anders moet zoeken."],
        ["Kies wie je benadert", "Bekijk de volgende selectie en bepaal zelf met wie je contact opneemt."],
      ],
      previewTitle: "Zie hoe klantfeedback terugkomt in de volgende selectie.",
      feedbackLabel: "Feedback van de klant",
      feedback: "We zoeken iemand die zelf nieuwe zakelijke klanten vindt.",
      whyLabel: "Relevante ervaring",
      why: "Vond en benaderde zelf nieuwe zakelijke klanten.",
      finalTitle: "Bekijk Scout met een vacature uit je praktijk.",
      finalBody: "Neem een lastige intake mee. We laten zien hoe Scout je feedback gebruikt bij het verdere zoeken.",
    },
    en: {
      eyebrow: "For recruitment agencies",
      title: "Less time searching. More time with candidates.",
      intro: "Turn what your client really needs into a shortlist that is worth reviewing.",
      sectionTitle: "Turn client feedback into a sharper search.",
      points: [
        ["Capture the real brief", "Turn the intake into a clear search direction."],
        ["Test the direction", "Review an initial shortlist and tell Scout what should change."],
        ["Contact relevant candidates", "See who fits the brief and decide who to approach."],
      ],
      previewTitle: "From feedback to a more relevant profile.",
      feedbackLabel: "Client feedback",
      feedback: "More experience personally winning new clients.",
      whyLabel: "Why review",
      why: "Documented experience in direct client acquisition.",
      finalTitle: "Bring a difficult vacancy.",
      finalBody: "See how Scout can make a complex brief more focused.",
    },
  },
  about: {
    nl: {
      eyebrow: "Over Philoo",
      title: "Een duidelijker vertrekpunt voor elke zoektocht.",
      intro: "Philoo richt zich op Scout: recruitmentsoftware die jouw context en feedback gebruikt om relevante kandidaten te vinden.",
      sectionTitle: "Gebouwd rond wat je echt bedoelt.",
      sectionBody: "Een functietitel vertelt zelden het hele verhaal. Scout gebruikt jouw uitleg en feedback op kandidaten om de zoekrichting scherper te maken.",
      principles: [
        ["Context vóór zoekwoorden", "Begin met wat het werk en het team echt vragen."],
        ["Redenen bij elk voorstel", "Zie welke bekende ervaring een profiel relevant maakt."],
        ["Jij kiest wie je benadert", "Scout ondersteunt de zoektocht; mensen nemen de beslissing."],
      ],
      founderLabel: "Oprichter",
      founderName: "Syb Janmaat",
      founderRole: "Founder, Philoo",
      founderQuote: "Ik bouw Philoo Scout om recruiters een scherper startpunt voor elke zoektocht te geven.",
      finalTitle: "Vind je volgende kandidaat.",
      finalBody: "Bekijk hoe context en feedback de zoekrichting scherper maken.",
    },
    en: {
      eyebrow: "About",
      title: "A clearer starting point for every search.",
      intro: "Philoo is focused on Scout: recruitment software that uses your context and feedback to find relevant candidates.",
      sectionTitle: "Built around what you actually mean.",
      sectionBody: "A job title rarely tells the whole story. Scout uses your explanation and candidate feedback to sharpen the search direction.",
      principles: [
        ["Context before keywords", "Start with what the work and the team really require."],
        ["Reasons behind suggestions", "See which known experience makes a profile relevant."],
        ["You decide who to contact", "Scout supports the search; people make the decision."],
      ],
      founderLabel: "Founder",
      founderName: "Syb Janmaat",
      founderRole: "Founder, Philoo",
      founderQuote: "I’m building Philoo Scout to give recruiters a sharper starting point for every search.",
      finalTitle: "Find your next candidate.",
      finalBody: "See how context and feedback can sharpen the search direction.",
    },
  },
  demo: {
    nl: {
      eyebrow: "Plan een demo",
      title: "Bekijk Scout in actie.",
      intro: "Neem een vacature mee waarvoor je kandidaten zoekt. We lopen samen door de aanpak.",
      points: [
        ["Bespreek je zoekvraag", "Leg uit welk werk iemand moet doen en wat belangrijk is voor je team."],
        ["Bekijk een selectie", "Zie welke ervaring in het profiel staat en welke vragen nog openstaan."],
        ["Bepaal of Scout past", "Bespreek je huidige aanpak en wat je in de praktijk nodig hebt."],
      ],
      bookingTitle: "Kies een moment in de agenda van Syb.",
      bookingBody: "De agenda opent in een nieuw tabblad. Daar zie je de beschikbare tijden in je eigen tijdzone.",
      bookingCta: "Open de agenda",
      fallback: "Liever mailen?",
      fallbackEmail: "hello@philoo.nl",
      note: "Er wordt pas een afspraak gemaakt wanneer je die zelf in Calendly bevestigt.",
    },
    en: {
      eyebrow: "Book a demo",
      title: "See Scout in action.",
      intro: "Bring a role you are hiring for. We will walk through the approach together.",
      points: [
        ["Discuss your search", "Explain the work someone needs to do and what matters to your team."],
        ["Review a shortlist", "See how Scout separates known experience from open questions."],
        ["Decide whether Scout fits", "Discuss your current approach and what you need in practice."],
      ],
      bookingTitle: "Choose a time in Syb’s calendar.",
      bookingBody: "The schedule opens in Calendly in a new tab. You will see current times and your time zone there.",
      bookingCta: "Open the calendar",
      fallback: "Prefer email?",
      fallbackEmail: "hello@philoo.nl",
      note: "An appointment is only created after you confirm it yourself in Calendly.",
    },
  },
} as const;
