import { ArrowRightIcon, BuildingIcon, CheckCircleIcon, SlidersIcon, UsersIcon } from "@/components/Icons";
import { SiteFooter } from "@/components/SiteFooter";
import { AnalyticsPageView, TrackedAnchor } from "@/components/site/Analytics";
import { PhilooMark } from "@/components/site/PhilooMark";
import { SiteHeader } from "@/components/site/SiteHeader";
import { CALENDLY_URL, type Language } from "@/lib/i18n";

const paired = { nl: "/over", en: "/en/about" };
const copy = {
  nl: {
    hero: ["OVER PHILOO", "Software bouwen voor recruitment, zonder onnodige complexiteit.", "Philoo bouwt software, AI en automatisering voor recruiters en recruitmentbureaus. We richten ons op concrete processen waar standaardsoftware niet altijd genoeg helpt."],
    what: ["WAT WE DOEN", "Gespecialiseerd in recruitmentsoftware.", "Philoo werkt specifiek aan software voor recruitment. Dat kan een eigen Philoo-product zijn, zoals CV Studio, of maatwerk voor een proces dat binnen een recruitmentbureau nog te veel handmatig werk vraagt.", [["Eigen producten", "Software voor veelvoorkomende problemen binnen recruitment."], ["Maatwerk", "Oplossingen voor processen die niet goed binnen standaardsoftware passen."], ["Bestaande systemen als basis", "Waar mogelijk bouwen we voort op het ATS, CRM en de andere software die al wordt gebruikt."]]],
    approach: ["ONZE AANPAK", "Praktisch beginnen. De recruiter houdt controle.", "Technologie moet recruitment eenvoudiger maken, niet ingewikkelder. Daarom beginnen we liever met een duidelijk probleem en bouwen we van daaruit verder.", [["Begin bij het probleem", "Eerst begrijpen waar tijd verloren gaat of een proces vastloopt."], ["Bouw alleen wat nodig is", "Geen groot nieuw systeem wanneer een gerichte oplossing genoeg is."], ["Sluit aan op de praktijk", "Software moet passen bij hoe recruiters daadwerkelijk werken."], ["Houd mensen in controle", "AI en automatisering ondersteunen het proces. De recruiter blijft verantwoordelijk voor de keuzes."]]],
    trust: ["PHILOO", "Een gespecialiseerd softwarebedrijf voor recruitment.", "Philoo werkt met recruitmentbureaus aan praktische softwareproducten en maatwerkoplossingen."],
    cta: ["Welke stap in je recruitmentproces kan eenvoudiger?", "Bespreek het met Philoo. We kijken graag mee of software, AI of automatisering praktisch kan helpen."],
    labels: ["Eigen producten", "Maatwerk", "Bestaande systemen als basis", "Begin bij het probleem", "Bouw alleen wat nodig is", "Sluit aan op de praktijk", "Houd mensen in controle", "Kennismaken", "Liever mailen?"],
  },
  en: {
    hero: ["ABOUT PHILOO", "Building recruitment software without unnecessary complexity.", "Philoo builds software, AI and automation for recruiters and recruitment agencies. We focus on practical processes where standard software does not always go far enough."],
    what: ["WHAT WE DO", "Software built for recruitment.", "Philoo focuses on software for recruitment. That can be a Philoo product such as CV Studio, or custom software for a process that still requires too much manual work at a recruitment agency.", [["Philoo products", "Software for practical recruitment problems."], ["Custom software", "Solutions for recruitment processes that standard software cannot support well."], ["Built around existing systems", "Where possible, we build on the ATS, CRM and software already in use."]]],
    approach: ["OUR APPROACH", "Start practical. Keep recruiters in control.", "Technology should make recruitment simpler, not more complicated. We prefer to start with a clear problem and build from there.", [["Start with the problem", "First understand where time is being lost or a process is getting stuck."], ["Build only what is needed", "No large new system when a focused solution is enough."], ["Match how recruiters work", "Software should fit the way recruiters actually work."], ["Keep people in control", "AI and automation support the process. Recruiters remain responsible for the decisions."]]],
    trust: ["PHILOO", "A specialised software company for recruitment.", "Philoo works with recruitment agencies on practical software products and custom solutions."],
    cta: ["Which recruitment process could work better?", "Discuss it with Philoo. We are happy to explore whether software, AI or automation could help."],
    labels: ["Philoo products", "Custom software", "Built around existing systems", "Start with the problem", "Build only what is needed", "Match how recruiters work", "Keep people in control", "Get in touch", "Prefer email?"],
  },
} as const;

const itemIcons = [BuildingIcon, SlidersIcon, UsersIcon, CheckCircleIcon];

export function AboutPage({ lang }: { lang: Language }) {
  const c = copy[lang];
  return <div className="site-page"><SiteHeader lang={lang} languageHrefs={paired} /><AnalyticsPageView event="site_page_view" language={lang} /><main>
    <section className="relative overflow-hidden border-b border-[#EDEEFA]"><div className="hero-ambient absolute inset-0" /><div className="relative mx-auto grid max-w-[1240px] gap-8 px-5 py-12 sm:px-8 sm:py-16 lg:grid-cols-[1.05fr_.75fr] lg:items-center lg:px-10 lg:py-20"><div><p className="text-xs font-black tracking-[.08em] text-[#563DFF]">{c.hero[0]}</p><h1 className="mt-4 max-w-[700px] text-[clamp(2.55rem,4.7vw,4.7rem)] font-bold leading-[1.02] tracking-[-.04em] text-[#091238]">{c.hero[1]}</h1><p className="mt-5 max-w-[650px] text-[1.05rem] leading-8 text-[#4D5679]">{c.hero[2]}</p><div className="mt-7 flex flex-wrap gap-3"><TrackedAnchor className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-[#563DFF] px-6 text-base font-bold text-white" event="calendly_cta_click" href={CALENDLY_URL} language={lang} rel="noopener noreferrer" sourceCategory="calendly" target="_blank">{c.labels[7]}<ArrowRightIcon className="h-5 w-5" /></TrackedAnchor><a className="inline-flex min-h-12 items-center rounded-xl px-3 text-sm font-semibold text-[#30395F] underline-offset-4 hover:underline" href="mailto:hello@philoo.nl">hello@philoo.nl</a></div></div><div aria-hidden="true" className="mx-auto grid h-56 w-56 place-items-center rounded-full bg-[#F2F0FF] shadow-[0_20px_60px_rgba(86,61,255,.1)]"><PhilooMark className="h-24 w-24 object-contain" /></div></div></section>
    <section className="px-5 py-12 sm:px-8 sm:py-16 lg:px-10"><div className="mx-auto max-w-[1240px]"><Intro data={c.what} /><div className="mt-8 grid gap-4 md:grid-cols-3">{c.what[3].map(([title, body]) => <article className="rounded-2xl border border-[#E1E4F2] bg-white p-6" key={title}><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#F0EEFF] text-[#563DFF]"><BuildingIcon className="h-5 w-5" /></span><h3 className="mt-4 text-lg font-bold text-[#11183B]">{title}</h3><p className="mt-2 leading-7 text-[#56607E]">{body}</p></article>)}</div></div></section>
    <section className="border-y border-[#EEF0F8] bg-[#FCFCFF] px-5 py-12 sm:px-8 sm:py-16 lg:px-10"><div className="mx-auto max-w-[1240px]"><Intro data={c.approach} /><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{c.approach[3].map(([title, body], i) => { const Icon = itemIcons[i]; return <article className="rounded-2xl border border-[#E2E5F2] bg-white p-5" key={title}><Icon className="h-5 w-5 text-[#563DFF]" /><h3 className="mt-4 font-bold text-[#11183B]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#56607E]">{body}</p></article>; })}</div></div></section>
    <section className="px-5 py-12 sm:px-8 sm:py-16 lg:px-10"><div className="mx-auto flex max-w-[1240px] flex-col gap-6 rounded-3xl border border-[#E2E0FF] bg-[#FBFAFF] p-7 sm:p-10 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-black tracking-[.08em] text-[#563DFF]">{c.trust[0]}</p><h2 className="mt-3 text-[clamp(1.8rem,3vw,2.7rem)] font-bold leading-tight tracking-[-.04em] text-[#0B1239]">{c.trust[1]}</h2><p className="mt-3 text-[#596180]">{c.trust[2]}</p></div><div className="shrink-0 text-sm leading-7 text-[#30395F]"><strong>Philoo Pte. Ltd.</strong><br />68 Circular Road, #02-01<br />049422 Singapore<br /><a className="font-semibold underline-offset-4 hover:underline" href="mailto:hello@philoo.nl">hello@philoo.nl</a></div></div></section>
    <section className="px-5 pb-12 sm:px-8 sm:pb-16 lg:px-10"><div className="mx-auto flex max-w-[1240px] flex-col gap-5 rounded-3xl bg-[linear-gradient(118deg,#FBFAFF,#F4F2FF)] p-7 sm:p-10 md:flex-row md:items-center md:justify-between"><div><h2 className="text-[clamp(1.8rem,3vw,2.7rem)] font-bold leading-tight tracking-[-.04em] text-[#0B1239]">{c.cta[0]}</h2><p className="mt-3 max-w-[700px] text-[#596180]">{c.cta[1]}</p></div><div className="flex flex-col items-start gap-2"><TrackedAnchor className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-[#563DFF] px-6 font-bold text-white" event="calendly_cta_click" href={CALENDLY_URL} language={lang} rel="noopener noreferrer" sourceCategory="calendly" target="_blank">{c.labels[7]}<ArrowRightIcon className="h-5 w-5" /></TrackedAnchor><span className="text-sm text-[#596180]">{c.labels[8]} <a className="font-semibold text-[#30395F] underline-offset-4 hover:underline" href="mailto:hello@philoo.nl">hello@philoo.nl</a></span></div></div></section>
  </main><SiteFooter lang={lang} /></div>;
}

function Intro({ data }: { data: readonly [string, string, string, readonly (readonly [string, string])[]] }) { return <div className="max-w-[720px]"><p className="text-xs font-black tracking-[.08em] text-[#563DFF]">{data[0]}</p><h2 className="mt-3 text-[clamp(2rem,3.4vw,3rem)] font-bold leading-tight tracking-[-.04em] text-[#0B1239]">{data[1]}</h2><p className="mt-4 text-[1.05rem] leading-7 text-[#596180]">{data[2]}</p></div>; }
